spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

#spring.data.mongodb.uri: mongodb://localhost:27017/mongodb
#spring.data.mongodb.uri: ${MONGODB_URI}
#spring.data.mongodb.database: test

spring.jpa.hibernate.ddl-auto: create
hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#spring.datasource.url: jdbc:mysql://localhost:3306/db_example
#spring.datasource.username: springuser
#spring.datasource.password: ThePassword
